### ISSUE TITLE
Typeclass-based model?

### ISSUE THREAD

**Issue by 4lex1v** [kclay/rethink-scala#29]
As i can see from the README example, ATM the only way to marshal my date into something that can be stored is to extend the `Document` type. Is there any way to do this using typeclasses? Or at least write a converter Model <-> Rethink Document?

**Comment by kclay** [comment]
You don't have to extend `Document` anymore, you can do
```scala
case class MyModel(date:DateTime)

r.table[MyModel].insert(MyModel(DateTime.now())).run 
```

Use 0.4.7-SNAPSHOT, would this work for your case?
