### ISSUE TITLE
Example documentation is wrong about Version

### ISSUE THREAD

**Issue by jateenjoshi** [kclay/rethink-scala#39]
As of release 4.6 (perhaps even further back), Version2 is not the right version to use for this driver. The documentation in the readme.md is confusing and mentions both Version1 and Version2 as the versions to use. Version1 doesn't seem to be available anymore (through code) and Version2 in the code is deprecated. 

The case class for Version2 is deprecated but the builder in Versions trait for Version2 is not deprecated, which can lead to more confusion. 

Version3 however seems to work fine.

Can we make that a little clearer on the documentation?

**Comment by ShengC** [comment]
More up-to-date examples are here,
https://github.com/kclay/rethink-scala/blob/master/core/src/test/scala/example/blocking/Tutorial.scala
https://github.com/kclay/rethink-scala/blob/master/core/src/test/scala/example/async/Tutorial.scala

Note that the real-time subscription is not supported in current shape of the driver. Hopefully it can be added some time soon...
